10-git-config: don't try to configure git if .gitconfig.lock exists
Without this, I got the error

    error: could not lock config file ~/.gitconfig: File exists

for each 'git config' command in my startup files whenever I ran shell
scripts with #!/bin/bash. I still don't know the root cause of the
error.